DefaultContentLanguage = "en"
baseURL = "https://loveourlocals.org/"
theme = "simplemap"
publishDir = "../firebase/public/"
defaultContentLanguageInSubdir = true
[languages]
    [languages.en]
        title = "Love Our Locals"
        weight = 1
        languageCode = "en-us"
     [languages.it]
        title = "Love Our Locals"
        weight = 2
        languageCode = "it-it"
[params]
    MapboxAccessToken = ""
    MapboxTheme = "mapbox://styles/mapbox/light-v10"
    GooglePlacesKey = ""
    GeoJSON = "https://storage.googleapis.com/helpmybusiness-752eb.appspot.com/poi/poi.gjson?v2"
    EnableIPtoCoords = true
    FirestoreCollection = "poi"
    FiresBaseHosting = true
    FirebaseApiKey = ""
    FirebaseApiKeyAuthDomain = ""
    FirebaseProjectId = ""
    FirebaseAppId = ""
    FirebaseMeasurementId = ""

